version: '2'
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
  